spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/user_crud_test}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  test:
    database:
      replace: none

server:
  port: 0
